[tox]
envlist =
    py{312,313,314}-test
    py{312,313,314}-{astropydev,legacy,latest}-test
    py{312,313,314}{,-syn}-cov
    py312-numexpr-mkl-cov

isolated_build = true

[testenv]
setenv =
    astropydev: PIP_EXTRA_INDEX_URL = https://pypi.anaconda.org/astropy/simple
passenv = *
extras =
    test
deps =
    cov: pytest-astropy
    cov: pytest-cov
    syn: synphot
    legacy: numexpr==2.11.0
    legacy: numpy==2.1.0
    legacy: scipy==1.15.0
    legacy: matplotlib==3.10.0
    legacy: astropy==7.0.0
    astropydev: astropy>=0.0.dev0
    numexpr: numexpr>=2.11
conda_deps=
    mkl: mkl_fft
conda_channels=
    mkl: https://software.repos.intel.com/python/conda/
    mkl: conda-forge
conda_install_args=
    mkl: --override-channels
commands_pre=
    pip list
commands=
    test: pytest {posargs}
    cov: pytest {posargs} --cov-config=pyproject.toml --cov-report=xml --cov-report=term-missing --cov=poppy poppy/tests/

[testenv:docbuild]
extras =
    docs
conda_deps =
    pandoc
commands=
    sphinx-build docs docs/_build

[testenv:codestyle]
skip_install = true
description = check package code style
deps =
    pycodestyle
commands =
    pycodestyle poppy

[testenv:flake8]
exclude= .git,__pycache__, test*
max-line-length = 120
